{
 "title": "emissary",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected routers",
   "type": "stat",
   "description": "Number of connected routers",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "transport_connections_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "stat",
   "description": "Total bandwidth",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(transport_inbound_bandwidth_total[$__rate_interval]) + rate(transport_outbound_bandwidth_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bandwidth usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((rate(transport_inbound_bandwidth_total[$__rate_interval]) + rate(transport_outbound_bandwidth_total[$__rate_interval])) / subsystem_bandwidth_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tunnel build success rate",
   "type": "gauge",
   "description": "What percentage of tunnel build requests succeed",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tunnel_build_success_count) / (sum(tunnel_build_success_count) + (sum(tunnel_build_failure_count) or vector(0))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tunnel test success rate",
   "type": "gauge",
   "description": "What percentage of tunnel tests succeed",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tunnel_test_success_count) / (sum(tunnel_test_success_count) + sum(tunnel_test_failure_count)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NetDb query success rate",
   "type": "gauge",
   "description": "What percentage of router info queries succeed",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(netdb_num_router_info_query_success_count) / (sum(netdb_num_router_info_query_failure_count) + sum(netdb_num_router_info_query_success_count)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transit tunnels",
   "type": "stat",
   "description": "Number of active transit tunnels",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "transit_tunnels_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Transit bandwidth",
   "type": "stat",
   "description": "Total transit bandwidth",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(transit_inbound_bandwidth_total[$__rate_interval]) + rate(transit_outbound_bandwidth_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transit bandwidth usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((rate(transit_inbound_bandwidth_total[$__rate_interval]) + rate(transit_outbound_bandwidth_total[$__rate_interval])) / subsystem_transit_bandwidth_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Tunnels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Outbound tunnels",
   "type": "stat",
   "description": "Number of outbound tunnels",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tunnel_outbound_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inbound tunnels",
   "type": "stat",
   "description": "Number of inbound tunnels",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tunnel_inbound_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pending tunnels",
   "type": "stat",
   "description": "How many local tunnels are in the process of being built",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tunnel_pending_inbound_count + tunnel_pending_outbound_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transit started",
   "type": "gauge",
   "description": "Percentage of transit tunnel requests that started a transit tunnel\n\nTransit tunnels that were accepted but were unable to start are not included",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(transit_tunnels_total_count) / (sum(transit_build_request_count)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transit rejected",
   "type": "gauge",
   "description": "Percentage of transit tunnel requests that were rejected",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(transit_tunnels_rejected_count) / sum(transit_build_request_count) * 100 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transit accepted",
   "type": "gauge",
   "description": "Percentage of transit tunnel requests that were accepted",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(transit_tunnels_accepted_count) / sum(transit_build_request_count) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IBGWs",
   "type": "stat",
   "description": "Number of transit IBGWs",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "transit_num_ibgws", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "OBEPs",
   "type": "stat",
   "description": "Number of transit OBEPs",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "transit_num_obeps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Participants",
   "type": "stat",
   "description": "Number of transit participants",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "transit_num_participants", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tunnel build rate",
   "type": "timeseries",
   "description": "Rate of tunnel build successes and failures",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(tunnel_build_success_count[$__rate_interval])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(tunnel_build_failure_count[$__rate_interval])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Tunnel build durations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by(le) (rate(tunnel_build_durations_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tunnel tests",
   "type": "timeseries",
   "description": "Rate of tunnel test successes and failures",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate(tunnel_test_success_count[$__rate_interval])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(tunnel_test_failure_count[$__rate_interval])",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Tunnel test durations (ms)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum by (le) (rate(tunnel_test_durations_bucket[$__rate_interval]))",
     "legendFormat": "Durations, ms"
    }
   ]
  },
  {
   "title": "Dropped fragments",
   "type": "timeseries",
   "description": "Number of dropped I2NP fragments at OBEP/IBEP",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(tunnel_dropped_fragment_count[$__rate_interval])",
     "legendFormat": "fragments"
    }
   ]
  },
  {
   "title": "Transit messages",
   "type": "timeseries",
   "description": "Rate of routed and dropped transit tunnel messages",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "rate(transit_routed_messages_count[$__rate_interval])",
     "legendFormat": "routed"
    },
    {
     "expr": "rate(transit_dropped_messages_count[$__rate_interval])",
     "legendFormat": "dropped"
    }
   ]
  },
  {
   "title": "Build request rate",
   "type": "timeseries",
   "description": "Rate of transit tunnel build requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rate(transit_build_request_count[$__rate_interval])",
     "legendFormat": "requests"
    }
   ]
  },
  { "title": "NetDb", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Floodfills",
   "type": "stat",
   "description": "Total number of known floodfills",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "netdb_floodfill_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active queries",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "netdb_active_query_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "description": "Average query duration",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(netdb_query_durations_sum[$__range]) / increase(netdb_query_durations_count[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Depth",
   "type": "stat",
   "description": "Average number of routers queried during a LS/RI lookup",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(netdb_num_queried_sum[$__range]) / increase(netdb_num_queried_count[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of queries",
   "type": "timeseries",
   "description": "Success/failure rate of router info and lease set queries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "rate(netdb_num_lease_set_query_success_count[$__rate_interval])",
     "legendFormat": "ls success"
    },
    {
     "expr": "rate(netdb_num_lease_set_query_failure_count[$__rate_interval])",
     "legendFormat": "ls failure"
    },
    {
     "expr": "rate(netdb_num_router_info_query_success_count[$__rate_interval])",
     "legendFormat": "ri success"
    },
    {
     "expr": "rate(netdb_num_router_info_query_failure_count[$__rate_interval])",
     "legendFormat": "ri failure"
    }
   ]
  },
  {
   "title": "Query durations",
   "type": "heatmap",
   "description": "How long it takes to conclude a successful query",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum by (le) (rate(netdb_query_durations_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of queries",
   "type": "heatmap",
   "description": "How many routers are queried per RI/LS query",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "sum by (le) (rate(netdb_num_queried_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Transport manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Dial success rate",
   "type": "gauge",
   "description": "What percentage of outbound connections succeed",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum(transport_dial_failure_count) / sum(transport_initiated_count))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query success rate",
   "type": "gauge",
   "description": "What percentage of router info queries for outbound connections succeed",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(transport_ri_query_successes) / (sum(transport_ri_query_successes) + (sum(transport_ri_query_failures) or vector(0))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Handshake success rate",
   "type": "gauge",
   "description": "What percentage of NTCP2/SSU2 handshakes succeed",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(ntcp2_handshake_success_count) + (sum(ssu2_handshake_success_count))) /\n((sum(ntcp2_handshake_failure_count) + sum(ntcp2_handshake_success_count)) + (sum(ssu2_handshake_success_count) + sum(ssu2_handshake_failure_count))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection accept rate",
   "type": "gauge",
   "description": "What percentage of connections are accepted",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(transport_accepted_connections_count) / (sum(transport_accepted_connections_count) + sum(transport_rejected_connections_count)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NTCP2 connections",
   "type": "stat",
   "description": "Number of NTCP2 connections",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ntcp2_connection_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IPv4 connections",
   "type": "stat",
   "description": "Number of IPv4 connections",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "transport_ipv4_router_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SSU2 connections",
   "type": "stat",
   "description": "Number of SSU2 connections",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ssu2_active_connection_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IPv6 connections",
   "type": "stat",
   "description": "Number of IPv6 connections",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "transport_ipv6_router_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connection rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "rate(transport_connections_opened_count[$__rate_interval])",
     "legendFormat": "opened"
    },
    {
     "expr": "rate(transport_connections_closed_count[$__rate_interval])",
     "legendFormat": "closed-{{reason}}"
    }
   ]
  },
  {
   "title": "Dial failures",
   "type": "timeseries",
   "description": "Rate of dial failures",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "rate(transport_dial_failure_count[$__rate_interval])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  { "title": "NTCP2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Handshake rate",
   "type": "timeseries",
   "description": "NTCP2 handshake success/failure rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "rate(ntcp2_handshake_success_count[$__rate_interval])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(ntcp2_handshake_failure_count[$__rate_interval])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Connection rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "rate(ntcp2_connections_opened_count[$__rate_interval])",
     "legendFormat": "opened"
    },
    {
     "expr": "rate(ntcp2_connections_closed_count[$__rate_interval])",
     "legendFormat": "closed-{{reason}}"
    }
   ]
  },
  {
   "title": "Message rate",
   "type": "timeseries",
   "description": "NTCP2 message rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "rate(ntcp2_num_outbound_msgs[$__rate_interval])",
     "legendFormat": "outbound"
    },
    {
     "expr": "rate(ntcp2_num_inbound_msgs[$__rate_interval])",
     "legendFormat": "inbound"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ntcp2_outbound_bw_count[$__rate_interval])",
     "legendFormat": "outbound"
    },
    {
     "expr": "rate(ntcp2_inbound_bw_count[$__rate_interval])",
     "legendFormat": "inbound"
    }
   ]
  },
  {
   "title": "NTCP2 message block count",
   "type": "heatmap",
   "description": "How many message blocks each NTCP2 message block contains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "sum by (le) (rate(ntcp2_blocks_per_msg_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages sizes",
   "type": "heatmap",
   "description": "NTCP2 inbound message sizes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "sum by (le) (rate(ntcp2_msg_sizes_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NTCP2 handshake durations",
   "type": "heatmap",
   "description": "How long it takes to establish an NTCP2 connection",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "sum by (le) (rate(ntcp2_handshake_duration_buckets_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "SSU2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "targets": [
    {
     "expr": "rate(ssu2_connection_count[$__rate_interval])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Connection rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "targets": [
    {
     "expr": "rate(ssu2_connections_opened_count[$__rate_interval])",
     "legendFormat": "opened"
    },
    {
     "expr": "rate(ssu2_connections_closed_count[$__rate_interval])",
     "legendFormat": "closed-{{reason}}"
    }
   ]
  },
  {
   "title": "Packet rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "targets": [
    {
     "expr": "rate(ssu2_ob_pkt_count[$__rate_interval])",
     "legendFormat": "outbound"
    },
    {
     "expr": "rate(ssu2_ib_pkt_count[$__rate_interval])",
     "legendFormat": "inbound"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ssu2_inbound_bytes_count[$__rate_interval])",
     "legendFormat": "inbound"
    },
    {
     "expr": "rate(ssu2_outbound_bytes_count[$__rate_interval])",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "Retransmitted packets",
   "type": "timeseries",
   "description": "What is the rate of packet retransmissions\n\nThat is, how many packets are retransmitted at a time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "targets": [
    {
     "expr": "rate(ssu2_retransmission_count[$__rate_interval])",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Dropped packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "targets": [
    {
     "expr": "rate(ssu2_dropped_pkts[$__rate_interval])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Duplicate packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "targets": [
    {
     "expr": "rate(ssu2_duplicate_pkt_count[$__rate_interval])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Relay rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
   "targets": [
    {
     "expr": "rate(ssu2_relay_failure_count[$__rate_interval])",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "rate(ssu2_relay_success_count[$__rate_interval])",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Handshake rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
   "targets": [
    {
     "expr": "rate(ssu2_handshake_success_count[$__rate_interval])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(ssu2_handshake_failure_count[$__rate_interval])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Handshake durations",
   "type": "heatmap",
   "description": "How long does it take to establish an SSU2 connection",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 153 },
   "targets": [
    {
     "expr": "sum by (le) (rate(ssu2_handshake_duration_buckets_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer test result (IPv4)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
   "targets": [
    {
     "expr": "rate(ssu2_ipv4_peer_test_result_count[$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Peer test result (IPv6)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
   "targets": [
    {
     "expr": "rate(ssu2_ipv6_peer_test_result_count[$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "SSU2 session durations",
   "type": "heatmap",
   "description": "What is the duration of an SSU2 session",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
   "targets": [
    {
     "expr": "sum by (le) (rate(ssu2_session_durations_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ACK durations",
   "type": "heatmap",
   "description": "How long it takes to receive an ACK for a packet",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 },
   "targets": [
    {
     "expr": " sum by (le) (rate(ssu2_ack_receive_times_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inbound fragments",
   "type": "heatmap",
   "description": "How many fragments do inbound packets have",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 177 },
   "targets": [
    {
     "expr": "sum by (le) (rate(ssu2_inbound_fragment_count_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound fragments",
   "type": "heatmap",
   "description": "How many fragments do outbound packets have",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 177 },
   "targets": [
    {
     "expr": "sum by (le) (rate(ssu2_outbound_fragment_count_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inbound packet sizes",
   "type": "heatmap",
   "description": "Sizes of inbound packets",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
   "targets": [
    {
     "expr": "sum by (le) (rate(ssu2_ib_pkt_sizes_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}